name: DJ Salisbury
favicon: null
layout_spectrum: 0.34525034693069756
typography_spectrum: 0.8419109813403338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2023173444904387
  lightness: 0.16020494047552347
  saturation: 0.4280447692144662
  rhythmicContrast: 0.6113789326045662
purpose: []
