name: DJ Salisbury
favicon: null
layout_spectrum: 0.34525034693069756
typography_spectrum: 0.66404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#95bccd'
    - '#7a9591'
    - '#2e444d'
    - '#4d7887'
    - '#70492f'
  brandStrength: 0.2023173444904387
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
